### ISSUE TITLE
Multisite not working

### ISSUE THREAD

**Issue by eresik** [ryancramerdesign/ProcessWire#1773] opened 2016-04-11 06:37 UTC
Multisite not working

Need at
https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/ProcessWire.php#L640
change
```
$hostConfig = function_exists("ProcessWireHostSiteConfig") ? ProcessWireHostSiteConfig() : array();
```
to
```
$hostConfig = function_exists("\ProcessWire\ProcessWireHostSiteConfig") ? ProcessWireHostSiteConfig() : array();
```

**Comment by ryancramerdesign** [comment] 2016-04-12 10:20
Thanks @eresik I've pushed the fix for this. I've updated it to detect either root namespace file or ProcessWire namespace file, as folks upgrading from PW2 to PW3 won't have a namespace in their index.config.php file.

**Comment by isellsoap** [comment] 2016-09-30 07:03
@eresik This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:03 UTC
Labels: Fixed
