### ISSUE TITLE
InputfieldPageListSelectMultiple module bug

### ISSUE THREAD

**Issue by MrEd69** [ryancramerdesign/ProcessWire#701] opened 2014-09-30 19:01 UTC
Hello, I am not sure if I am the first one to find this bug, but...
 
How to reproduce:
Create field FieldsetTabOpen (lets name test_tab)
Create field Page (lets name test), choose Multiple pages, and type PageListSelectMultiple
 
Add the fields to template:
 
test_tab
test
test_tab_END
 
The field "test" is not sortable. The reason is because the InputfieldPageListSelectMultiple.init is called before the tabs are rendered.
My very quick workaround was to move the init method call into setTimeout, but I am not sure if this the correct choice.
 
wire/modules/Inputfield/InputfieldPageListSelect/InputfieldPageListSelectMultiple.module:88 now looks like the line below.
"setTimeout(function() { InputfieldPageListSelectMultiple.init($('#{$this->id}_items')); }, 200);" . 

Processwire version 2.4

Topic in forum: https://processwire.com/talk/topic/7774-inputfieldpagelistselectmultiple-module-bug/

**Comment by isellsoap** [comment] 2015-08-20 06:57
@MrEd69 Can this be closed? Please look also to other PRs or issues of you (if there are any), that could be closed. Thanks!

**Comment by isellsoap** [comment] 2016-03-10 07:47
@ryancramerdesign Since @MrEd69 doesn’t close the issue, can you do it?

**Comment by isellsoap** [comment] 2016-09-30 06:49
@MrEd69 This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 06:49 UTC
Labels: Already Fixed
