### ISSUE TITLE
PW 3.0.10 — InputfieldImageListToggle double icon

### ISSUE THREAD

**Issue by fijha** [ryancramerdesign/ProcessWire#1736] opened 2016-03-08 22:59 UTC
![inputfieldimagelisttoggle](https://cloud.githubusercontent.com/assets/17672049/13619245/4c4a730a-e588-11e5-8d3f-75a3318e474c.png)

When I set image field visibility to "**Closed + Load only when opened (AJAX) †**" the `InputfieldImageListToggle` icon is doubled on ajax load

— the icon is already there, so no need to insert it again on ajax load…

`<a href="#" class="InputfieldImageListToggle HideIfEmpty"><i class="fa fa-th"></i></a>`

**Comment by ryancramerdesign** [comment] 2016-04-05 13:15
Thanks @fijha I've pushed a fix for this issue.

**Comment by isellsoap** [comment] 2016-09-30 07:03
@fijha This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:03 UTC
Labels: Fixed
