### ISSUE TITLE
3.0.18: $pages->find($selectorArray) problems with special characters at the end of a string

### ISSUE THREAD

**Issue by phas0r** [ryancramerdesign/ProcessWire#1855] opened 2016-05-31 17:31 UTC
```
$pages->find("template=custom, my_field='2-299 (1/80)'"); // works
$pages->find([["template" => "custom"], ["my_field" => "2-299 (1/80)"]]); // works

$mySelector = array();
$mySelector["template"] = "custom";
$mySelector["my_field"] = "2-299 (1/80)";
$pages->find($mySelector); // returns no page

$pages->find(["template" => "custom", "my_field" => "2-299 (1/80)"]); // returns no page
```
The same goes for many or maybe all special characters at the end of the string.

**Comment by ryancramerdesign** [comment] 2016-06-09 18:36
Thanks @phas0r I've pushed a fix for this issue.

**Comment by isellsoap** [comment] 2016-09-30 07:05
@phas0r This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:05 UTC
Labels: Fixed
