### ISSUE TITLE
"create new field" on template edit issue

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1889] opened 2016-06-22 14:55 UTC
I experience a missbehaviour when adding a new field to template via "create new field" link.

It opens modal, I set new field and hit save and see an empty admin page inside the modal:

![image](https://cloud.githubusercontent.com/assets/370148/16271412/2f224022-389a-11e6-8253-a32e6aeac00d.png)

**Comment by adrianbj** [comment] 2016-06-22 15:07
Just to confirm that it's happening for me too. Here is the problem line and the commit it was added on:
https://github.com/ryancramerdesign/ProcessWire/commit/8c02030b66ffcce02500d0624ac3ebc71ef96cdc#diff-1af7c5cf398c4f8ce33b808cd88a842aR1407

**Comment by ryancramerdesign** [comment] 2016-06-29 09:35
Thanks guys, I've pushed a fix. Thanks Adrian for tracking down the source – that must have been a tough one to find. Still not sure why that change causes the issue, but I've wrapped it in a conditional to prevent it.

**Comment by isellsoap** [comment] 2016-09-30 07:06
@somatonic This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:06 UTC
Labels: Fixed
