### ISSUE TITLE
[InputfieldMarkup] Inputfield::collapsedNever

### ISSUE THREAD

**Issue by mikerockett** [ryancramerdesign/ProcessWire#853] opened 2015-01-07 05:59 UTC
This property doesn't work as intended. If I set:

``` php
$field->collapsed = Inputfield::collapsedNever;
```

The field collapses by default.

**Comment by ryancramerdesign** [comment] 2015-01-18 11:34
I can't seem to duplicate that here. If a field is set to collapsedNever, then I don't even have the option to close it (no icon). What version of PW? Does your InputfieldMarkup have a label set, or no label?

**Comment by mike-anthony** [comment] 2015-01-18 13:01
2.5.13 (I didn't upgrade to 2.5.14 due to module config not saving).

If I only use a value, I need not set the `collapsed` property. If I add the label, and set it to `collapsedNever`, the field is always collapsed, and I cannot expand it.

Here's a screencast: http://ge.tt/3ey64p82

**Comment by mike-anthony** [comment] 2015-01-25 08:45
Update: with 2.5.6, setting it to `collapsedNever` makes it disappear altogether...

**Comment by mike-anthony** [comment] 2015-02-19 15:12
Can you still not reproduce this? (Or has it been fixed and I haven't noticed?)

**Comment by teppokoivula** [comment] 2015-02-21 17:14
For the record: I'm seeing same behaviour. This issue seems to affect InputfieldMarkup because it extends InputfieldWrapper, and is apparently caused by the block of code (currently) starting from [line 329 of InputfieldWrapper.php](https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/core/InputfieldWrapper.php#L329); $collapsed evaluates to true (9), isEmpty() returns true (no children found), and instanceof InputfieldWrapper also returns true.

Not entirely sure why InputfieldMarkup extends InputfieldWrapper, but perhaps it should (at least) have it's own isEmpty() method? The one from InputfieldWrapper doesn't seem to make much sense here :)

**Comment by mikerockett** [comment] 2016-09-05 13:24
Just an update on this: I'm currently working with the new Jumplinks config page, adding a fieldset with `collapsedNever` set, containing a checkbox with no `collapsed` setting. The fieldset collapses by default, and I'm unable to expand it.

**Closed** 2021-03-01 19:30 UTC
Labels: Can't reproduce, Need More Information
