### ISSUE TITLE
3.0.x devns $pages->touch($page) throwing error (typo)

### ISSUE THREAD

**Issue by CanRau** [ryancramerdesign/ProcessWire#1763] opened 2016-03-24 21:06 UTC
Just tried out new touch() method and gave it a single page like
`$pages->touch($page)`
but it's saying the following
```Notice: Undefined variable: page in /wire/core/PagesEditor.php on line 1119```
I'm on 3.0.9 guess you added some line breaks later on..

while this works fine
`$pages->touch(array($page->id));`
so page is of course valid..

aha, found it [L1124](https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/PagesEditor.php#L1124) should read `$pages->id`

Nice feature by the way!

**Comment by ryancramerdesign** [comment] 2016-04-06 11:29
Thanks @CanRau good find! I've pushed the fix for that.

**Comment by isellsoap** [comment] 2016-09-30 07:03
@CanRau This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:03 UTC
Labels: Fixed

**Comment by CanRau** [comment] 2016-09-30 12:43
uh thanks for closing @isellsoap forgot to do it myself
