### ISSUE TITLE
Module PageEdit - Setting Default "view" location/action

### ISSUE THREAD

**Issue by ottogal** [ryancramerdesign/ProcessWire#1830] opened 2016-05-16 10:41 UTC
When you change the setting _Default "view" location/action_ to _New Window/Tab_, a click to the View tab wouldn't work anymore - you'd have to use the dropdown list. (The other options don't have this issue.)

BTW: Wouldn't it be more consistent to let also the green View Button in the pages tree respect this same setting?

**Comment by rolandtoth** [comment] 2016-05-20 10:27
Confirmed here too.

**Comment by ryancramerdesign** [comment] 2016-06-08 15:00
> When you change the setting Default "view" location/action to New Window/Tab, a click to the View tab wouldn't work anymore - you'd have to use the dropdown list. (The other options don't have this issue.)

Thanks @ottogal I have fixed the issue and it will appear in this weeks' commits. 

> BTW: Wouldn't it be more consistent to let also the green View Button in the pages tree respect this same setting?

The purpose of the PageList is to navigate to another place. Whereas the purpose of PageEdit is about editing and working with a specific page. That's why this setting is specific to the PageEdit module. In PageList, if you want to open in new window, then you'd do a cmd+click. Or if you want to open in a modal, then you just click and hold the view link for a second. We haven't yet added a panel option to it, but may add that too.

**Comment by ottogal** [comment] 2016-06-09 16:04
Thank you Ryan, I see the point.

**Comment by isellsoap** [comment] 2016-09-30 07:04
@ottogal This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:04 UTC
Labels: Fixed
