### ISSUE TITLE
Homepage showing instead of 404 in some cases

### ISSUE THREAD

**Issue by devsmo** [ryancramerdesign/ProcessWire#754] opened 2014-10-23 08:08 UTC
When the URL contains a space, accented character or some other invalid characters Processwire shows the home page instead of the 404 page.

I think this issue is caused by these lines in .htaccess:
> ErrorDocument 404 /index.php
> [...]
> RewriteCond %{REQUEST_URI} "^/~?[-_.a-zA-Z0-9/]*$"

I notice that this issue is fixed on processwire.com but not in the default installation of the CMS. Is there a reason for displaying the home page, and what is the best way to fix this?

**Comment by isellsoap** [comment] 2016-09-30 08:36
@devsmo This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 08:36 UTC
Labels: Can't reproduce
