### ISSUE TITLE
uninstalling a textformatter module

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1986] opened 2016-08-25 07:49 UTC
I tried to uninstall a textformatter module, in my case SuperSmartyPants.
It seemed to work ("uninstall" checkbox was checkable).

When I refreshed the modules page, the module was still installed.
Turned out that the textformatter was used in a couple of fields, that had to be fixed then I could successfully uninstall.

I would expect that I cannot uninstall and have a hint for which fields the formatter is used,
or an information "do you really want to remove the formatter for fields 1,2,3" and an automatic cleaning of those fields with the uninstall... or so...

**Comment by adrianbj** [comment] 2016-08-27 15:58
Duplicate of https://github.com/ryancramerdesign/ProcessWire/issues/603

**Closed** 2016-09-23 16:42 UTC
Labels: Feature Request
