### ISSUE TITLE
WYSIWYG not returning LanguagesPageFieldValue

### ISSUE THREAD

**Issue by NicoKnoll** [ryancramerdesign/ProcessWire#1306] opened 2015-07-22 16:07 UTC
Hey,
if I have my body field as TextareaLanguage and activate "Markup / HTML with image handling" and insert an image into the second language the field won't return an "LanguagesPageFieldValue" object anymore but only the string even with $page->of(false);

**Comment by ryancramerdesign** [comment] 2015-07-25 13:33
What's the API scenario where you are seeing it? The LanguagesPageFieldValue basically pretends to be a text field, so that handlers that don't know anything about multi-language can still see and output it as a text field. For instance, most Inputfields no nothing about LanguagesPageFieldValue, so that distinction is managed by LanguagesSupport / LanguageSupportFields. A value that passed through an Inputfield (since you mentioned WYSIWYG) will always have a string value rather than a LanguagesPageFieldValue, because the Inputfield is rendered and processed separately for each language.

**Comment by NicoKnoll** [comment] 2015-07-25 16:34
Well my scenario is that I tried to use $page->getLanguageValue('body', $german) and got an error. Than I tried $page->of(false); var_dump($page->body); and got only a string. 

Afterwards I changed the content of "body" to text only and it worked.

Somehow I think the main point is that there is kind of a conflict between getting the languagevalue object and the automatic image-handling option.

**Comment by ryancramerdesign** [comment] 2015-07-26 12:25
@NicoKnoll I understand now, and you are right, this one needs to maintain the LanguagesPageFieldValue. See the latest commit, which corrects that.

**Comment by isellsoap** [comment] 2015-08-27 10:43
@NicoKnoll Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by isellsoap** [comment] 2016-09-30 07:01
@NicoKnoll This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:01 UTC
Labels: Conversation, Fixed
