### ISSUE TITLE
Custom users cannot be edited from the page tree or found in admin search ($user->editable())

### ISSUE THREAD

**Issue by JanRomero** [ryancramerdesign/ProcessWire#1877] opened 2016-06-12 16:35 UTC
I keep a special class of users with a custom UserTemplate within the non-admin part of the page tree. These users are supposed to be administrated by standard users who have a certain role. When these administrator users (non-superusers) navigate to a custom user’s edit page via Access->Users this works fine. What doesn’t work is accessing the edit page via **page tree actions** or the **admin search** bar, because PagePermissions::userEditable() will return false unless it is called from process ProcessUser.

This forces administrator users to deviate from their usual workflow by necessitating they take a specific route to the edit page instead of going through the page tree or admin search as they would with normal pages.

The following [condition should be removed from PagePermissions.module](https://github.com/ryancramerdesign/ProcessWire/blob/d45781d5af21e6aa6b838463a2acc4bcecbcc1a4/wire/modules/PagePermissions.module#L231), IMHO:

    // if the current process is something other than ProcessUser, they don't have permission
    if($this->wire('process') != 'ProcessUser') {
    	return false;
    }

**Comment by LostKobrakai** [comment] 2016-06-12 18:20
This is expected behavior as users are meant to be edited by ProcessUser only. But I'm with you, that the page-tree actions should still work and deligate to ProcessUser in this case.

**Comment by ryancramerdesign** [comment] 2016-06-28 11:07
Currently it would only work if the user was superuser. But I think it's okay to open up the permissions a bit here for users that have user-admin permission. I've updated it so that you should be able to get working edit links from within PageList and PageLister.

**Comment by isellsoap** [comment] 2016-09-30 10:20
@JanRomero This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 10:20 UTC
Labels: Completed
