### ISSUE TITLE
A page save randomly doesn't show save message.

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1490] opened 2015-11-05 19:36 UTC
I'm not sure what it's all about. Here's that.

I have locally a blank testinstall 2.6.18. I noticed this since some time that when I save a page in page editor backend, sometimes it doesn't show the green message on top that the page is saved. Just skips it. This happens only randomly.

I updated now to latest and still same happens.

To reproduce you just open about page and change title "aasdad" hit save. Just change title or also leave it same and hit save until it happens. Sometimes it doesn't happen for 5-6 saved, but suddenly...

**Comment by matjazpotocnik** [comment] 2015-11-05 20:43
I tried very hard (in Chrome and IE), saved at least 100 times and couldn't reproduce on 2.6.21

**Comment by somatonic** [comment] 2015-11-05 21:16
Could this be something locally? I have no idea why this would happen randomly. Sorry, looks like I'm joking but it's definately not, it just happend two times in 20 saves. Chrome Mac with MampPro install. PHP 5.4.13.

**Comment by somatonic** [comment] 2015-11-05 21:19
Then again I can hit save 50 times and it works. Then suddenly. If there's nobody else observing this just ignore. I'll try again on other installs.

**Comment by adrianbj** [comment] 2015-11-05 21:20
I actually have a similar issue with my EmailNewUser module - when you create a new user it is supposed to generate a few messages letting you know their details and that they were successfully emailed their invite, but every now and then, the messages aren't displayed, even though everything actually worked as it was meant to. 

I assume your observations are related to what I am seeing?

**Comment by somatonic** [comment] 2015-11-05 21:22
Totally yes. In my momory I noticed this even on older 2.4 installes, and those are not locally. Just randomly not showing save messages.

**Comment by somatonic** [comment] 2015-11-05 21:26
I just hit save without changing anything. So it would be session related I'd guess. Like It's choking or something.

**Comment by LostKobrakai** [comment] 2015-11-06 08:25
Do you have SystemNotifications installed? I've noticed this several times when debugging hooks to the save process, but only with the module installed.

**Comment by somatonic** [comment] 2015-11-06 10:53
No I don't have SystemNotificatons installed. Not stable enough :)

**Comment by ryancramerdesign** [comment] 2015-11-06 14:34
I'm aware of the issue in SystemNotifications occurring occasionally and have not been successful in figuring out why... yet. Though that's the only thing that's "not stable enough" in SystemNotifications that I'm aware of. But just reading that the issue occurred for you, even without SystemNotifications installed, made me look at the issue entirely differently–something clicked. 

The notices (whether in SystemNotifications or without it) must be getting removed by some other AJAX request. This would make sense, since the queued notices get removed from the session, and populated to $notices when the session starts. Then if a redirect occurs, it re-queues them. But what if some AJAX request came in and just ended with a die() or exit(). Those notices wouldn't get re-queued and would essentially be lost. I think that's what's happening. 

Given that, I've just pushed a potential fix for this which doesn't remove the notices from the $session until the admin.php template is included, and we know they've been output. While I've not been able to duplicate the issue without SystemNotifications, I can now see how it could occur. My hope is that this fix might resolve the issue both with and without SystemNotifications. Please let me know.

**Comment by craigrodway** [comment] 2015-11-11 16:10
I haven't noticed/experienced the main issue reported here, but just a gotcha/FYI for when using notices in front-end template code.

On a site under development (2.6.23) I was wondering why, on subsequent pages, I kept seeing a notice I had previously. As this change takes away the automatic removal of notices from the session, I have to call `$session->removeNotices();` manually to clear them.

Not sure if this was/should be intentional; or if this fix should/can be applied admin-side only?

**Comment by isellsoap** [comment] 2016-03-18 14:19
@somatonic Could you please close this issue? Thank you!

**Comment by lparikka** [comment] 2016-04-06 10:11
What do you say about @craigrodway comment above? Shouldn't the notices be cleared on page reload as they have been cleared before? Or do we need to call $session->removeNotices() every time?

**Closed** 2016-09-30 08:57 UTC
Labels: Fixed! Please Confirm
