### ISSUE TITLE
PW 3.0.10 — Repeater dynamic loading (AJAX) in editor — CKEditor (inline) won't load custom CSS!

### ISSUE THREAD

**Issue by fijha** [ryancramerdesign/ProcessWire#1722] opened 2016-03-05 11:58 UTC
**Repeater dynamic loading (AJAX) in editor:**

— when set to "**Existing and new items**" CKEditor (inline) won't load "**Custom Editor CSS style (inline mode)**" "/site/modules/InputfieldCKEditor/contents-inline.css"…

— when set to "**New items only**" it loads fine…

**Comment by ryancramerdesign** [comment] 2016-04-05 12:41
Thanks @fijha I've pushed a fix for this issue.

**Comment by isellsoap** [comment] 2016-09-30 07:02
@fijha This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:02 UTC
Labels: Fixed
