### ISSUE TITLE
Date picker for date field not showing inside Table 2.5.12

### ISSUE THREAD

**Issue by alexanderpt** [ryancramerdesign/ProcessWire#842] opened 2014-12-29 19:02 UTC
JS/CSS datepicker files not loading if template has Table with date. If put another date field in template then both working.

**Comment by ryancramerdesign** [comment] 2015-01-04 10:35
Thanks, I have located the issue. It's specific to InputfieldTable.module, so will post an update to the ProFields board within the next day or so.

**Comment by isellsoap** [comment] 2015-08-27 10:40
@alexanderpt Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by isellsoap** [comment] 2016-03-10 07:30
@ryancramerdesign Could you please close this issue? @alexanderpt doesn’t seem to do so.

**Comment by isellsoap** [comment] 2016-09-30 06:59
@alexanderpt This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 06:59 UTC
Labels: Fixed
