### ISSUE TITLE
$users->get(ID) returns Page-instance instead of NullPage

### ISSUE THREAD

**Issue by yckart** [ryancramerdesign/ProcessWire#1833] opened 2016-05-17 15:45 UTC
```php
$users->get(1)->name // => "home"
```
*ProcessWire 3.0.18 devns*

**Comment by ryancramerdesign** [comment] 2016-06-09 09:42
Thanks @yckart that's a great find, I have pushed a fix. The issue was a matter of caching.

**Comment by isellsoap** [comment] 2016-09-30 07:04
@yckart This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:04 UTC
Labels: Fixed
