### ISSUE TITLE
Deleting file within a repeater doesn't change style Reno Theme

### ISSUE THREAD

**Issue by TomS-** [ryancramerdesign/ProcessWire#2037] opened 2016-09-15 10:15 UTC
Only tested this with a repeater, on Chrome.

A file field within a repeater, if you press delete, the block background turns red, however hovering out will turn it back to the standard background. It's not clearly shown which files are going to be deleted on save.

**Comment by ryancramerdesign** [comment] 2016-09-21 12:43
Thanks @TomS- I've pushed a fix for this issue.

**Comment by isellsoap** [comment] 2016-09-30 07:08
@TomS- This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:08 UTC
Labels: Fixed
