### ISSUE TITLE
$pages->find(integer_field=1|0) treats 0 as null

### ISSUE THREAD

**Issue by ryanlath** [ryancramerdesign/ProcessWire#851] opened 2015-01-06 17:57 UTC
If you have an integer field, these work:
$pages->find("int_field=0")
$pages->find("int_field=1|2|3|4")

These throw error: 
Error: Exception: SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 
$pages->find("int_field=1|0|2")
$pages->find("int_field=1|0")

Is this expected behavior?

**Comment by ryancramerdesign** [comment] 2015-01-18 19:26
Nope, that's not the intended behavior. I have fixed it locally (along with the null vs. 0 differentiation with integers), and I'll be testing here for a day or two before committing it to dev. Thanks for finding it.

**Comment by isellsoap** [comment] 2015-08-27 10:41
@ryanlath Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Closed** 2015-08-27 15:31 UTC
Labels: Fixed, Minor bug
