### ISSUE TITLE
Installation: Choosing InnoDB doesn't work for initial tables

### ISSUE THREAD

**Issue by esrch** [ryancramerdesign/ProcessWire#1765] opened 2016-03-29 10:11 UTC
When choosing to use InnoDB as a database during installation, this choice is not taken into account when creating the initial tables. I noticed that the $options variable is not passed in to the function profileImport and profileImportSQL functions in install.php. But correcting this didn't solve the problem, and all initial tables were still created using the MyISAM database engine.

**Comment by ryancramerdesign** [comment] 2016-04-06 13:51
Thanks @esrch I've pushed an update that should correct this issue.

**Comment by isellsoap** [comment] 2016-09-30 07:03
@esrch This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:03 UTC
Labels: Fixed
