### ISSUE TITLE
showListFilters option in ProcessField module has no effect

### ISSUE THREAD

**Issue by yckart** [ryancramerdesign/ProcessWire#1867] opened 2016-06-09 01:12 UTC
Filters are always visible (collapsed), maybe this option could removed?

**Comment by ryancramerdesign** [comment] 2016-06-10 14:07
Yes, that can be removed. I have deleted it. Thanks.

**Comment by isellsoap** [comment] 2016-09-30 07:05
@yckart This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:05 UTC
Labels: Fixed
