### ISSUE TITLE
Sanitizer::date() woot?

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1483] opened 2015-10-29 23:45 UTC
I wanted to "validate" a date input, and thought I can use sanitizer date() 

```
$input = "11-2015";
$dateValid = $sanitizer->date($input", "n-Y");
```

But it didn't work and while starring for a long time on that source code of Sanitizer::date() I think I misunderstood it maybe, but then still I can't help but think it's full of bugs. :)

1. The min max doesn't work as var names are wrong.

````
$min = ctype_digit("$options[max]") ? (int) $options['max'] : (int) wireDate('ts', $options['max']);
if($value > $max) return null;
```
I'm not sure what this part is good for:

```
if(!is_string($value) && !is_int($value)) $value = $this->string($value);
if(ctype_digit("$value")) {
	// value is in unix timestamp format
	$ts = (int) $value;
	// make sure it resolves to a valid date
	$value = date('Y-m-d H:i:s', $ts);
	$value = strtotime($ts);
} else {
	if(!is_string($value)) $value = $this->string($value);
}
````

**Comment by ryancramerdesign** [comment] 2015-11-02 11:10
Thanks Soma, I have pushed a fix for this.

**Comment by isellsoap** [comment] 2016-03-10 07:39
@somatonic Can you close this issue please? Thank you!

**Comment by isellsoap** [comment] 2016-09-30 07:01
@somatonic This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:01 UTC
Labels: Fixed
