### ISSUE TITLE
Strings are not extracted to translate from ProcessLanguageTranslator module

### ISSUE THREAD

**Issue by jtherczeg** [ryancramerdesign/ProcessWire#623] opened 2014-08-30 15:49 UTC
Installed the latest PW dev branch (ver. 2.4.15) on localhost. In the Language Translation Files list I clicked Edit for /wire/modules/LanguageSupport/ProcessLanguageTranslator.module. In the Language Translator screen for ProcessLanguageTranslator, that opened, the one and only following string, I mean code snippet appeared:

, '$this->_n(', '$this->_x(

My environment: Apache 2.4.9, PHP 5.5.12, MySQL 5.6.17

**Comment by isellsoap** [comment] 2016-03-10 07:26
@jtherczeg Can this issue be closed?

**Comment by isellsoap** [comment] 2016-09-30 06:58
@jtherczeg This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 06:58 UTC
Labels: Fixed
