### ISSUE TITLE
3.0.5 CroppableImages Issue

### ISSUE THREAD

**Issue by Notanotherdotcom** [ryancramerdesign/ProcessWire#1639] opened 2016-01-27 15:30 UTC
I think this is an easy one - all it needs to fix it is for the namespace to be added at the top. I don't think PW 3.x is automatically doing this because of a non-standard folder layout:

site/modules/
     -- CroppableImages
        -- FieldtypeCroppableImage
        -- InputfieldCroppableImage
        -- ProcessCroppableImage

...and then class names under them. Without adding the namespace, there's a namespace error along the lines of "Fatal error: Exception: Item 'FieldtypeCroppableImage' set to ProcessWire\Fieldtypes is not an allowed type"

I'll mention it in Horst's repo too, but would be good if the compiler could be adapted to pick up less standard folder layouts too (if that is indeed the issue).

**Comment by Notanotherdotcom** [comment] 2016-01-27 15:33
In fact, this would need to be picked up by the compiler else module authors would need to have a 2.x version and a 3.x version which could get tricky unless we change the modules directory to allow for both (and the module installer inside ProcessWire). Gives the module author a bit more flexibility then... but I think that conversation may have happened on the forums already - just thinking out loud!

**Comment by ryancramerdesign** [comment] 2016-01-31 13:46
Pete, I went ahead and installed CroppableImage, but everything worked on this end. No errors, and module appears to work normally in 3.0.6. I'm wondering about the directory structure you mentioned, as that doesn't look consistent with what I have here, or what it should be. In my case, it's all under /site/modules/FieldtypeCroppableImage/ with all the directories under it. It also had "classes" and "templatefiles" directories under it. Anyway, it technically *should* be installed under /site/modules/FieldtypeCroppableImage/ and not /site/modules/, since its a multi-component module. Is it possible that's what the issue is? Or maybe yours is missing the "classes" and "templatefiles" directories? I would try removing all the CroppableImage directories you've got in /site/modules/ and then do a Modules > Site > Clear compiled files. Then re-install a fresh copy under /site/modules/FieldtypeCroppableImage/. Does that fix it?

**Comment by isellsoap** [comment] 2016-09-30 08:55
@Notanotherdotcom Can this issue be closed?

**Comment by isellsoap** [comment] 2016-10-01 06:44
@Notanotherdotcom No input from you since January, I close this issue. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it.

**Closed by isellsoap** 2016-10-01 06:44 UTC
Labels: Can't reproduce
