### ISSUE TITLE
Fatal error in PageFinder when trying to add new language 

### ISSUE THREAD

**Issue by anilex** [ryancramerdesign/ProcessWire#893] opened 2015-01-31 01:38 UTC
```
Notice: Undefined variable: stmt in /<path>/wire/core/PageFinder.php on line 286
Fatal error: Call to a member function errorCode() on a non-object in /<path>/wire/core/PageFinder.php on line 286
```

When I try to add new language.
(latest dev 2.5.17, clean site-language install)

**Comment by isellsoap** [comment] 2015-08-26 07:12
@anilex Can this issue be closed?

**Comment by isellsoap** [comment] 2016-03-10 07:51
@ryancramerdesign Could you please close this issue? Thank you!

**Comment by isellsoap** [comment] 2016-09-30 06:54
@anilex This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 06:54 UTC
Labels: Fixed! Please Confirm
