### ISSUE TITLE
3.0.18: SVG images can be uploaded, but get deleted on next page edit

### ISSUE THREAD

**Issue by init2null** [ryancramerdesign/ProcessWire#1846] opened 2016-05-22 20:36 UTC
Here's a bug in the rewritten image field when using SVG files. SVGs upload without error and display thumbnails, but they have no trashcan icon and are deleted as soon as the page editor is reopened. Existing files uploaded with the old version of image are not deleted, but there's still no trashcan icon, so they can't be deleted at all.

Let me know if any more information is needed. Thanks!

**Comment by FlipZoomMedia** [comment] 2016-05-23 13:49
:+1: Same here. In addition, the description field and the name is missing. Left a SVG image, right a normal image (png, jpg, gif).

![pw-svg](https://cloud.githubusercontent.com/assets/708183/15472931/cb4030fe-20fd-11e6-83fe-b5480892274d.png)

**Comment by adrianbj** [comment] 2016-05-23 13:53
A little OT, but it seems that the description field is also missing from File fields.

**Comment by ryancramerdesign** [comment] 2016-06-09 15:02
Thanks, I've pushed a fix for this.

**Comment by isellsoap** [comment] 2016-09-30 07:05
@init2null This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:05 UTC
Labels: Fixed
