### ISSUE TITLE
No permission to edit image in repeater on home page

### ISSUE THREAD

**Issue by CaelanStewart** [ryancramerdesign/ProcessWire#2042] opened 2016-09-20 11:05 UTC
Hi All,

For clients, we create a role with the minimal permissions they require to manage the content on their site. However, one of our clients went to crop an image, and was confronted with this error message:

![2016-09-20 11_58_21-edit page_ home romney-marsh dev](https://cloud.githubusercontent.com/assets/11272013/18667710/a66b3442-7f29-11e6-8394-d8ff11b8ec96.png)

However, this only occurs if the image is inside a repeater field, and is on the home page. Any other page is fine.

Though, I was able to work around the issue by setting the access config for the repeater's internal templates.

If any other info is required, just let me know, and I'll get that to you.

**Comment by ryancramerdesign** [comment] 2016-09-21 10:35
What version of ProcessWire? I think we recently fixed a similar issue on the 3.x devns branch. Though if you are already using 2.8.x or 3.x then we'd want to get a closer look. Thanks.

**Comment by CaelanStewart** [comment] 2016-09-21 16:39
Hi,

Latest 3.0.33. 

Regards,
Caelan Stewart

**Comment by CaelanStewart** [comment] 2016-09-21 16:41
Also, I forgot to mention. This is happening on some other pages now. I've just left work, so I'll check that out tomorrow. 

Regards,
Caelan Stewart

**Comment by CaelanStewart** [comment] 2016-09-22 08:54
OK, I've just had a look, and it is indeed happening on other pages.
![2016-09-22 09_47_27-program manager](https://cloud.githubusercontent.com/assets/11272013/18742002/f0f1c4b4-80a9-11e6-9e6b-44306ba3b01c.png)

Role name: 'user'
Role permissions:
`page-edit, page-sort, page-lister, page-view, profile-edit`

Template: 'about'
Template access for role 'user':
`View Pages, Edit Pages`

If there's anything else you need to replicate the issue, let me know.

**Comment by ryancramerdesign** [comment] 2016-09-22 12:51
Thanks, I think I've tracked this one down and have pushed a fix.

**Comment by isellsoap** [comment] 2016-09-30 07:08
@CaelanStewart This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:08 UTC
Labels: Fixed

**Comment by CaelanStewart** [comment] 2016-09-30 09:24
@isellsoap, cheers! Good to see fast response to issues here.

Great work.
