### ISSUE TITLE
The new linkAbstractor - issues

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1660] opened 2016-02-03 14:55 UTC
This code is now falsifying correct links.

My structure:
/de/page1/
/de/page2/
/de/page2/subpage/

/en/page1/
/en/page2/
(/en/page2/subpage/ not existing: no subpage for En, EN was not checked)

1. I set a link in /en/page1/  
to /de/page2/subpage/
After saving I see this /en/page2/subpage/  (/de/ -> /en/)

2. I set a link in /de/page1/  
to /de/page2/subpage/
After saving I see this /page2/subpage/ (/de/ removed)

Is this repeatable? (Safari)
[UPDATE - tested with Firefox]

**Comment by ryancramerdesign** [comment] 2016-02-04 10:48
So far I can't duplicate here, but I'm also running a slightly newer version of MarkupQA (that handles this), so I've just pushed that version to devns. Though the changes are primarily for dealing with local URLs that have http/https schemes in them.

If you can, please grab the latest commit/version and add the following to your /site/config.php file:
```````
$config->debugMarkupQA = true; 
```````
This will make it report verbose debug info whenever you edit or save the page. Though note MarkupQA only comes into action if some change is made to the field containing the links. Note what messages it reports in your notices at the top of the screen, and see if you can locate the one that's being incorrectly converted. If you find it, please paste the notice in here. 

A few questions for you:

- I'm assuming you have the LanguageSupportPageNames module installed and managing your /de/ and /en/ language segments, but just wanted to double check?
- For your /de/ or /en/ links that are getting updated incorrectly, are the /de/ links in the German version of the field, and the /en/ links in the English version of the field, or are they mixed (like an English text field that links to a German page?)
- Can you reproduce it on newly entered links? Or did the falsified links come from the original batch "apply HTML" operation?
- You mentioned "page1" and "page2" – are these just example names, or are those the literal names? I ask because they would potentially collide with pagination URL segments, which might be a potential source of confusion to MarkupQA. But I'm assuming you are just using those as examples... wanted to double check though. 

Thanks for helping to test/debug.

**Comment by tbba** [comment] 2016-02-04 11:23
Ok, i will test today...

Your questions
- LanguageSupportPageNames is active and I make use of the checkboxes to switch not needed languages off per page (these pages, that do not carry all languages, may be the probem here, actually)
- I try to avoid language cross linkings, where possible. 
- The tests were also with new links, that homored the language.
- page1,2.. were just example names. 
- plainlangiagetextarea/CKEditor fields. I verified the links by checking html source in CKE.
- (a next step for my check would be the disabling of Jumplinks - just in case redirects play a role here.  I am hesitating to do so because, deactivating probably means that all the many settings there get lost)

**Comment by tbba** [comment] 2016-02-04 12:15
The debugging code is a big help:

**TEST 1 - disappearing of default language path**
QA sees that there is something with one link (not valid/language path missing) but gives an alert in green (ok):
_
MarkupQA wakeupLinks no changes (field=body2, language=default): /label/historie/bravo/ => /label/historie/bravo/_

I am trying to fix that link to /de/label/historie/bravo/  using the page selector to be sure the new link exists

I am checking in CKE html source that the new link was entered /de/label/historie/bravo/  -OK

I click out of cke to defocus it (to circumvent the safari bug)

I check the link in CKE again, still there

Now I save the page

red warning:
_MarkupQA wakeupLinks PATH UPDATED (field=body2, page=/de/label/historie/, language=default): /de/label/historie/bravo/ => /label/historie/bravo/_

This is wrong: 
- The settings on my homepage has "de" set for the default language (in case the QA module is looking there for the path), not "", only the homepage should have no language path for the default language:
(the settings in LanguageSupportPageNames for url on startpage has the default setting NO redirect)

**Comment by tbba** [comment] 2016-02-04 13:24
TEST 2A - linking from EN to a page in DE (where EN is switched off in LanguageSupportPageNames)
This is complicated to explain. I will try :-)

A am in the languagetextara of a non-default language (en).
There, I create a new link in CKE
The CKE link-dialog is showing.
I use the page selector - for every page slected the language path is added: /en/
Now I try to select a page, where I know that in languagetextara the 2nd language, /EN/, is switched off.
The page is selectable and the link is shown with the "/en/" path 
(I expected that the page isn't offered in that language or that /de/ that I am asked to which of the valid languages I would like to link to instead)

I hit save
 
 The link to the page in the non-existing language (language active=false) was saved.
  MarkupQA sleepLinks (field=summary, page=/de/helga-pogatschar/titus-trash-tatar/, lang=en): => 

Funny: The "wrong" link actually works: Instead of a 404 the pages shows but with no fields rendered.
I expected a 404.
I looked closer: If I am not logged in, I get the 404; if I am logged in (superuser) I see an existing empty page. To me this looks like a bug (maybe unrelated).

I would expect a warning on QA that there is a link to a page in a not active language.

**Comment by ryancramerdesign** [comment] 2016-02-04 14:24
Regarding test 1, while I couldn't duplicate the issue exactly as you mentioned, I did spot potential issues and have pushed an update that I think will fix them. Are you able to try it out and see if it also resolves the issue you spotted with test 1?

After putting in the latest commits, do a Modules > Refresh before testing again, because the latest commit also includes an update to PagePathHistory module that may help as well. (PagePathHistory now supports multi-language). 

Regarding test 2, if I understand correctly, this sounds like correct behavior. PW won't validate whether a given page is active or published when you are linking to it. That's because very often people setup links while things are still unpublished or otherwise not yet activated. For instance, you might be setting up an entire section of pages and cross linking between them, well before you are ready to publish them. Or you might be linking to a page that requires login, and the user gets redirected to a login form if they don't have access. So MarkupQA is just looking for instances where your link resolves to a page, and abstracting the page ID into it so that it can continue resolving if the URL to it ever changes. 

As for linking to an EN page from within a DE field, you would have to enter such a link manually since PW is making the assumption that if you are editing text in DE, you probably want to link to pages in DE as well. However, as of the latest commit, you could insert the page link and just change the first segment (i.e. /de/path/ to /en/path/) and MarkupQA will take care of updating the rest of the path to be the /en/ version when you save, even if you are editing a field in DE.

**Comment by tbba** [comment] 2016-02-04 14:58
TEST 1 - Repeat with new PW files
- I did a module refresh after uploading the new files
- In CKE i fixed the link using the page-selector in the links-dialog.
- hit SAVE

RED warning:
MarkupQA wakeupLinks PATH UPDATED (field=body2, page=/de/label/historie/, language=default): /de/label/historie/bravo/ => /label/historie/bravo/

AND green warning:
MarkupQA sleepLinks (field=body2, page=/de/label/historie/, lang=default): => 

(The link is still reset.)

**Comment by tbba** [comment] 2016-02-04 15:18
regarding TEST 2
Setting an internal cross-language link is strongly recommended by GOOGLE to avoid, so I think it is correct what PW does. I wanted to test this anyway to see what happens. :-)
In such rare cases, having to set a link manually would be perfectly ok. And it is great that QA now can handle that.

I also think that PW is doing right by allowing to set links that would lead to 404 errors. (I would be very annoyed if I just temporarily unpublish a page and all internal links to it would be erased automatically.)

What I was wondering is that pages that have a language not checked are offered by the link tool in that language. It's so easy to make mistakes that way. Especially if you are the editor and not the developer.
Also, since content for language 2 can be a copy (fallback) of the default language1 (or a copy paste oversight) wrong links can easily sneak in language2. Correct? 
Since QA is so intelligent right now, how about some warning about a language cross-linking or a linking to a non existing language of that target page?
(The usual 404 checker software is great in detecting broken links. But, at least my tools cannot detect cross-language linking to valid targets as errors.)

**Comment by tbba** [comment] 2016-02-04 15:25
Maybe my language setup is unusual, where the default language has also a path? I did this to make your hreflang snippet work as intended and to make it easier to use separate sitemaps for the languages. And Google obviously likes this setup. My new website, where I try the new pw languages setup for the first time (instead of real individual language directories), ranks pretty well in all languages right from the start.

**Comment by ryancramerdesign** [comment] 2016-02-04 16:01
Regarding test 1, it looks like I've still got more work to do here. I think I need to focus on duplicating the situation you are seeing so that I can observe it rather than attempting more guesses. So I'll ask a few more questions, some of which I think you've already answered, but I just want to double check. 

1. Your default language is "de" correct?
2. You've configured your homepage to live at "/de/" rather than "/" ?
3. When editing your homepage, the page name for default language is "de" (or is it blank?)
4. For the link you inserted: "/de/label/historie/bravo/" did you insert this in the "de" textarea or the "en" textarea?

Regarding your points on test 2 and preventing or warning about links to a page/language that doesn't have the "active" checkbox checked – I think we may be feasible for us to provide a warning when that occurs, I will look into it further for sure. 

> Maybe my language setup is unusual, where the default language has also a path?

This is not unusual at all. I'd say it's more common than not. At least, I've used the same approach on all the multi-language installations I work on. Though I usually enforce the "/" for the homepage/default language URL, but the segment "/en/" for everything else (where "en" is my default language). 

Agreed on the hreflang attributes, Google seems to love them, once you get them right. :)

**Comment by tbba** [comment] 2016-02-04 16:29
Regarding my setup... (you can get access, if that helps):
- default language in language settings is "de".
- homepage (index) path in German (default) has "/" only, the rest of the pages from the default language have "/de/...".
- homepage (index) in English has "/en/" the rest of the pages from the Einglish have "/en/..." also.
- in the homepage-settings, language name1 (default) is "de" and language name2 is "en".
- The "de" link was inserted on the "de" part oft the languagetextarea-CKE.

**Comment by tbba** [comment] 2016-02-04 18:50
the good news, a lot of de->de links on the webpage _are_ in the process of being corrected, I started seeing on every page save notices like this appearing:
MarkupQA wakeupLinks PATH UPDATED (field=summary, page=/de/helium-vola/, language=default): /ernst-horn/ => /de/ernst-horn

**Comment by ryancramerdesign** [comment] 2016-02-05 11:17
I tried and tried and just could not duplicate the issue. Then as a test, I installed the PagePaths module, BAM! was finally able to reproduce it. 

Here's the issue, the PagePaths module does not support multi-language. I think if you uninstall that module, all should start working. Can you confirm?

In order to prevent others from running into the same thing, I'm currently working on some updates to the PagePaths module, and may have them ready today.

**Comment by tbba** [comment] 2016-02-05 11:48
How brilliant. - Indeed the website had been single language first and I used this module.
After a few tests the problem is solved!!!!!!!!!!!!!!!!!!

(Is the pagePathRedirect also a problem? I deactivated that one too, just in case. I can do what it does with Jumplinks also.)

**Closed** 2016-02-05 11:48 UTC
Labels: Need More Information, Potential Bug
