### ISSUE TITLE
Pages without Settings tab don't work with "Name format for children"

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1420] opened 2015-09-29 13:34 UTC
I realize that turning off the Settings tab is an "Advanced Mode" feature which are 'use at your own risk', but I thought it would be good to let you know about this anyway.

When creating a new page who's parent template uses "Name format for children", if the child page has the Settings tab disabled, the page cannot be saved. 

The error is "Can't save page . . . It has an empty name field"

**Comment by adrianbj** [comment] 2015-09-29 18:54
Duplicate of https://github.com/ryancramerdesign/ProcessWire/issues/1048

If you use the RestrictTabView module - it has an inbuilt workaround - it adds a hidden "name" field to the Content tab, which prevents the error you are seeing.

**Comment by thetuningspoon** [comment] 2015-09-29 19:01
Thanks for the link and module, Adrian. Of course it would be nice to see a fix for this in the core.

**Comment by ryancramerdesign** [comment] 2015-09-30 12:59
Thanks guys, I've pushed a fix for this. Please let me know if you run into any more trouble with it.

**Closed** 2015-11-05 22:20 UTC
Labels: Fixed
