### ISSUE TITLE
Conflict: InputField:Selector and FieldType:Comments

### ISSUE THREAD

**Issue by bcartier** [ryancramerdesign/ProcessWire#865] opened 2015-01-10 18:04 UTC
(Edited: Turns out to be a simpler problem and unrelated to the "Selector" Inputfield for Page Reference, sorry. The following is still an issue:)

Creating a new Comments field (called 'article_comments') in a template named 'articles''  results in the following error:

    SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'field_article_comments_votes' already exists

The error shows any time I edit a page using the 'articles' template, and also when I edit a page that has a Page reference field that might allow selection of Pages using the 'articles' template.

ProcessWire v2.5.14
Fieldtype: Comments v1.0.6
Comments Admin	v1.0.4

**Comment by ryancramerdesign** [comment] 2015-01-19 18:33
Are you still seeing this error in the latest dev? I think we got this one fixed last week. Kongondo reported the same error, though in a different context (Blog module), and I put in a fix for it. If that's not it, by any chance do you have another field in your system called `article_comments_votes`?

**Comment by isellsoap** [comment] 2016-09-30 14:05
@bcartier This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please add a comment to this issue and I re-open it.

**Closed by isellsoap** 2016-09-30 14:05 UTC
Labels: Conversation
