### ISSUE TITLE
PageFrontEdit.module conflicts with TemplateEngineFactory.module

### ISSUE THREAD

**Issue by dreerr** [ryancramerdesign/ProcessWire#1691] opened 2016-02-15 12:11 UTC
Due to priority order it is currently not possible to make TemplateEngineFactory.module work together with PageFrontEdit.module . It is not possible to set the priority of `addHookAfter('Page::render',…)` in TemplateEngineFactory.module:77 under 100.
It would be needed to set PageFrontEdit.module:170 hooks priority above 100. This is similar to the issue [here](https://github.com/ryancramerdesign/ProcessWire/issues/1218) if I am correct.

**Comment by ryancramerdesign** [comment] 2016-03-02 11:23
I can't see any problem with increasing the hook priority level here, I've bumped it to 102 in the latest commit.

**Comment by isellsoap** [comment] 2016-03-18 14:16
@dreerr Could you please close this issue? Thank you!

**Comment by isellsoap** [comment] 2016-09-30 10:19
@dreerr This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 10:19 UTC
Labels: Completed
