### ISSUE TITLE
Images uploading twice

### ISSUE THREAD

**Issue by eladnova** [ryancramerdesign/ProcessWire#1072] opened 2015-04-07 11:17 UTC
PW 2.5.24

When dragging an image to an image field, the image is uploading twice. IE I see two progress bars and then 2 images.

**Comment by ryancramerdesign** [comment] 2015-04-07 13:34
I don't see the issue here, and haven't had any other reports of it. Can you think of anything specific I need to configure in order to see this behavior? What browser and version, and what 3rd party modules do you have installed in /site/modules/? Anyone else reading this able to duplicate the issue? Thanks.

**Comment by jacmaes** [comment] 2015-04-08 16:26
I've experienced this also a few times, but I always assumed I somehow dragged and dropped incorrectly. I'm on Chrome Mac. If I see this again on 2.5.25, I'll give you my list of modules.

**Comment by jacmaes** [comment] 2015-04-10 16:07
It happens also on regular image fields, .i.e. those that do not use the Thumbnails module. I dragged and dropped five images onto the my image field, and 10 images got uploaded:

![duplicates](https://cloud.githubusercontent.com/assets/1206842/7091737/6d280264-dfac-11e4-8a46-d69527b01274.png)

**Comment by eladnova** [comment] 2015-04-18 14:42
I get this on both Chrome and Mac. Have yet to try other browsers.

Chrome: Version 42.0.2311.90 (64-bit)
Theme: Reno
ProcessWire: 2.5.24 dev 

Modules are:
FormBuilder (latest Dev)
HelperFieldLinks
InputfieldCKEditor
JqueryDataTables
MarkupSEO
MarkupSimpleNavigation
ModulesManager
ProcessAccessOverview
ProcessBatcher
ProcessChangelog
ProcessCroppableImage
ProcessDateArchiver
ProcessExportProfile
ProcessPageListerPro
ProcessWireConfig
ProcessWireUpgrade
TextformatterHannaCode

**Comment by teppokoivula** [comment] 2015-04-18 16:29
Can't reproduce this here either. In the lists above I see couple of common modules that I don't have installed here at the moment (FormBuilder, ProcessPageListerPro, ProcessWireConfig, and ProcessWireUpgrade) but not much more than that.

Does this also happen on a clean installation, and is it happening all the time or just randomly every now and then? Taking a look at network details would be interesting too; does the browser perform two POST requests? Does this happen with specific images, or is this entirely random too?

Having a minimal installation / site profile / site to test and reproduce this on would be hugely helpful.

**Comment by eladnova** [comment] 2015-04-18 21:30
@teppokoivula I'll remove those modules one by one and test during the week. 
When you mention looking at network details, is that via web inspector (chrome) ?

**Comment by teppokoivula** [comment] 2015-04-19 05:30
@eladnova Yeah, mainly the network tab, though thinking bout it now, not sure how useful that detail would be; just trying to get all the facts together :)

**Comment by jacmaes** [comment] 2015-04-21 09:07
The issue is gone for me on Chrome 43 beta with PW 2.5.27. A bug in a previous version of Chrome?

**Comment by isellsoap** [comment] 2016-09-30 13:51
@eladnova Can this issue be closed?

**Comment by isellsoap** [comment] 2016-10-01 06:51
@eladnova I close this issue as it seems fixed. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it.

**Closed by isellsoap** 2016-10-01 06:51 UTC
Labels: Can't reproduce
