### ISSUE TITLE
Page Name character replacements of ÆØÅ -- Scandinavian character support

### ISSUE THREAD

**Issue by klor** [ryancramerdesign/ProcessWire#816] opened 2014-12-07 07:02 UTC
Page Name replaces characters when generating the url slug part. For better support of Scandinavian characters, please make the following changes:

* æ=ae
* ø=o (or "oe")
* å=aa (å is currently set to å=a, but double-a is the correct translation into English)

## Module information

Title: Page Name
Class: InputfieldPageName
File: /wire/modules/Inputfield/InputfieldPageName/InputfieldPageName.module

**Comment by isellsoap** [comment] 2015-08-27 10:58
@klor Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by isellsoap** [comment] 2016-09-30 10:17
@klor This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 10:17 UTC
Labels: Completed

**Comment by teppokoivula** [comment] 2016-09-30 10:21
@isellsoap: not directly related to the issue, but please note that OP won't be able to reopen an issue you've closed. That's how GitHub works: only collaborators can reopen issues, including ones they've created themselves.

**Comment by isellsoap** [comment] 2016-09-30 10:29
@teppokoivula Thanks, that’s good to know. I will adjust the comments on future issues I close.
