### ISSUE TITLE
main-classic.scss overrides background settings of ckeditor modals

### ISSUE THREAD

**Issue by sunlix** [ryancramerdesign/ProcessWire#618] opened 2014-08-27 20:12 UTC
just observed the behavior of ckeditor modal ("source code" modal) at close icon, maybe there are other cases too.

the following line override the background css setting with none on hover state, so there are no more a background-image (close-icon) in this state.
https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/AdminTheme/AdminThemeDefault/styles/main-classic.css#L2950

may be it is sufficient to set the background-color to none to avoid the current behavior?

**Comment by isellsoap** [comment] 2016-10-01 09:27
@sunlix This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please add a comment to this issue and I re-open it.

**Closed by isellsoap** 2016-10-01 09:27 UTC
Labels: Minor bug
