### ISSUE TITLE
$page->prev $page->next don't work if $page->save was executed

### ISSUE THREAD

**Issue by mr-fan** [ryancramerdesign/ProcessWire#1359] opened 2015-08-24 12:48 UTC
See
https://processwire.com/talk/topic/10731-how-to-debug-page-prev-page-next-no-output-given/#entry101092

Setup is to save a counter field on the page. This uncache the page and prev/next are empty and won't work.

With option it works but this behaviour could be a bug since it only affect prev next?
$page->save(array("quiet" => true, "uncacheAll" => false));

regards mr-fan

**Comment by ryancramerdesign** [comment] 2015-09-22 15:46
Thanks @mr-fan I've pushed a fix for this issue, please let me know if it also corrects the issue there.

**Comment by isellsoap** [comment] 2016-03-10 07:34
@mr-fan Can you close this issue, please? Thank you!

**Comment by isellsoap** [comment] 2016-09-30 07:01
@mr-fan This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:01 UTC
Labels: Fixed
