### ISSUE TITLE
Button on children tab "Add new Page here" doesn't work

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1530] opened 2015-11-30 10:04 UTC
When I click that button, nothing happens...

**Comment by apeisa** [comment] 2015-11-30 18:54
Which version?

**Comment by somatonic** [comment] 2015-12-01 09:46
2.7, 2.71

I'm not sure whats up with it. I haven't looked into it closely. Just recieved a bug report and tested in 2 Installation and it's not working.

**Comment by ryancramerdesign** [comment] 2015-12-01 10:50
I'm not seeing the issue here, but that button I think is influenced by
javascript, so a JS error may prevent it from working. Do you see any JS
errors in your console?

**Comment by somatonic** [comment] 2015-12-01 11:10
No, no JS error. Also no modules or custom JS installed.

**Comment by ryancramerdesign** [comment] 2015-12-01 11:21
Okay, since I can't reproduce here, lets wait until we can find someone else to observe the same issue. Though if you can think of any factors that might be present, please let me know.

**Comment by somatonic** [comment] 2015-12-01 12:04
It's a report from a client, I never used this button. There's no JS or anything.

This button is different from all other buttons in that it's a link with a button inside and clicking the button isn't triggering the anchor. When I remove the <button> in inspector clicking the link works fine. 

It seems that some JS is preventing the click. When I insert a on.click event in the console for "a"'s it doesn't trigger. But it get's triggered when I use "a.mousedown".

**Comment by somatonic** [comment] 2015-12-01 12:50
Add this to your config. 

$config->pageEdit = array(
    'viewNew' => true,
);

Or

$config->pageEdit = array(
    'viewNew' => false,
);


Took me hours to find it.

**Comment by ryancramerdesign** [comment] 2015-12-07 11:50
Thanks, that helped me to reproduce the issue. I have pushed a fix. Also, for your pageEdit or pageList config arrays, I recommend doing this instead, so that you aren't wiping out the other settings:
`````
$config->pageEdit = array_merge($config->pageEdit, array(
  'viewNew' => false
)); 
`````

**Closed** 2016-03-09 10:23 UTC
Labels: Fixed
