### ISSUE TITLE
Images with a width matching that of maxWidth are not run through the image processer

### ISSUE THREAD

**Issue by cb2004** [ryancramerdesign/ProcessWire#1406] opened 2015-09-22 16:16 UTC
Consider the tag:

<?php echo $page->image_single->maxWidth(640)->url; ?>

If the image matches the width 640 then it is not run through the image process, meaning that most importantly for the site I am developing, quality is not set to 90 and it just loads the uploaded image.

Not sure if this affects any other scenarios where height/width match exactly.

**Comment by ryancramerdesign** [comment] 2015-09-23 19:36
Unless my caffeine level is running low, this appears to be the correct behavior. Whether you request a width() or a maxWidth() (or any of the other size functions) if the image already matches the requested dimension, it will use it. In the case of the maxWidth() method, if the image was equal to or less than the requested width, it would return it.

**Comment by cb2004** [comment] 2015-09-23 19:50
If that's expected behavior that is fine with me. I just always upload my jpegs at maximum quality as they are run through the processor and the quality comes down. I will just keep it in mind for future builds. Cheers Ryan.

**Comment by cb2004** [comment] 2015-09-25 09:49
Ok I am going to reopen this. An image with the tag <?php echo $page->image_single->size(960, 960)->url; ?> when the image is 960x960 is run through the image processor.

**Comment by horst-n** [comment] 2015-09-25 13:39
@ryancramerdesign: I consider this a bug, and I have sent a pull request in the past for this. I'm not sure, but I thought we have corrected this already, so that images with the exact (or a smaller size when upscaling is not allowed) are running through the processor so that the quality setting get applied?

**Comment by horst-n** [comment] 2015-09-25 13:42
yes, it is already in the dev-branch:
https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/core/ImageSizer.php#L408

**Comment by isellsoap** [comment] 2016-03-10 07:55
@cb2004 Can you please close this issue? Thank you!

**Comment by isellsoap** [comment] 2016-09-30 07:12
@cb2004 This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:12 UTC
Labels: Not a bug
