### ISSUE TITLE
Call to a member function getAllVariations() on null	

### ISSUE THREAD

**Issue by gazley** [ryancramerdesign/ProcessWire#1817] opened 2016-05-06 15:03 UTC
Just upgraded to 3.0.16 from .15

Trying to open a page: http://localhost:8888/processwire/page/edit/?id=1

I get the error:

File: .../Inputfield/InputfieldImage/InputfieldImage.module:157

```
147:                } else {
148:                    $page = new NullPage();
149:                }
150:                if($page->id && $this->wire('user')->hasPermission('page-edit-images', $page)) {
151:                    $modules->get('JqueryUI')->use('modal');
152:                } else {
153:                    $this->useImageEditor = 0;
154:                }
155:            }
156:            
157:            $this->variations = $this->value->getAllVariations();
158:            
159:            return parent::renderReady($parent, $renderValueMode);
160:        }
161:    
```

**Comment by cb2004** [comment] 2016-05-09 11:56
I saw the same error 1 commit before 3.0.17 was released. Upgrade to 3.0.17 and it should be fine.

**Comment by ryancramerdesign** [comment] 2016-06-03 14:43
I can confirm, upgrading should fix that one. Though please let me know if you continue to see it.

**Comment by isellsoap** [comment] 2016-09-30 06:46
@gazley This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 06:46 UTC
Labels: Already Fixed
