### ISSUE TITLE
Feature Request: Save & Edit Next

### ISSUE THREAD

**Issue by CaelanStewart** [ryancramerdesign/ProcessWire#1897] opened 2016-06-28 09:32 UTC
Hi All,

I find that often I will have to manually iterate through many pages to edit the same field(s). Save & Exit is good, and makes it a bit quicker. But Save & Edit Next should automatically save the current page, and open the edit page for the next page in the order they appear in the page tree. Would make those manual processing tasks a little more efficient.

**Comment by matjazpotocnik** [comment] 2016-06-28 10:38
Maybe you could use macrura's Prev/Next Tabs http://modules.processwire.com/modules/prev-next-tabs/

**Comment by CaelanStewart** [comment] 2016-06-28 10:56
That would involve one less click, but the same number of page loads as is already required. You would still need to click save, wait for the page to load, and then click next.

I know this is only a small thing, and would probably only take a very short amount of time to implement. But when you're editing many pages, it *feels* like it's making a big difference when the number of clicks and page-loads you have to go through is as low as possible.

**Comment by CaelanStewart** [comment] 2016-06-28 11:45
https://github.com/ryancramerdesign/ProcessWire/pull/1898

**Comment by ryancramerdesign** [comment] 2016-06-29 10:46
I agree on this feature, this is something I'd like to add. The only reason it's not there yet is because determining what is the "next" page–in a way that's scalable–is not that simple. One has to load all the siblings in order to make that determination. Think in terms of thousands or millions of pages. While we've got a `$page->next()` method in the API, it's not scalable unless you can provide to it a limited pagination set of siblings. A page being edited does not know what it's closest siblings are. It can only be determined by non-filtered pagination set that happens to include the current page. At larger scales, it's nearly impossible to determine without using a lot of horsepower. It's doable, but a little tricky, as it involves considering the sort settings applied to the parent (if sorting is not manual). Once I get the Page next() and prev() methods updated to be scalable, I'll add this feature. But I don't like to add features like this until I can be certain they'll work all the time regardless of scale. Though if there are a million siblings, chances are you aren't going to be "Save and Edit Next'ing" those anyway. :) But I'll try and take a closer look at this one this week. Thanks.

**Comment by teppokoivula** [comment] 2016-06-29 11:47
> Once I get the Page next() and prev() methods updated to be scalable, I'll add this feature.

Just a few days ago stumbled upon my own comment back from 2012 (I think) where I had disabled prev and next navigation, stating that they'll be re-enabled once scalability issues are solved. If you *do* find a scalable way to do this, I can finally get back to that ;-)

**Comment by isellsoap** [comment] 2016-09-30 10:20
@CaelanStewart This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 10:20 UTC
Labels: Completed, Feature Request
