### ISSUE TITLE
Reno Theme, Lister Pro: Add New opens in 2 windows

### ISSUE THREAD

**Issue by outflux3** [ryancramerdesign/ProcessWire#1963] opened 2016-08-06 19:37 UTC
This has been a longtime bug, but finally reporting it; If you click Add New on lister pro you get add new in a new page and also the page itself adds new, so you get 2 add new pages.

To reproduce this, you'd need to be in Reno Theme, using Lister Pro, and have edit links configured to open in new window.

**Comment by ryancramerdesign** [comment] 2016-08-16 10:17
Testing in PW 3.0.30 and ListerPro 1.1.0 I'm not seeing that issue here. When I click "add new" (either top of bottom button) only a single modal opens. What versions are you running? If the same as mine, are there any other modules installed that you can think of that might be affecting the behavior? Also curious if behavior changes if you reduce the displayed columns to be just "title". Thanks.

**Comment by Renobird** [comment] 2016-08-16 12:03
I haven't seen this on any of the installs I have, and I can't recreate it either.

**Comment by outflux3** [comment] 2016-08-16 12:55
To reproduce you have to set both View and Edit links to open in New Window.

**Comment by somatonic** [comment] 2016-08-16 13:39
Maybe it will help out a little and post a link where I posted a fix for similar issue 5 months ago: https://processwire.com/talk/topic/12732-incorrect-add-new-button-behaviour/

**Comment by ryancramerdesign** [comment] 2016-08-17 12:41
@outflux3 I think Soma and I must have had the same confusion on this one, as it looks like we both thought you were talking about modal windows (or at least I know I did). But you did clearly say "new window", and somehow I still thought we were talking about modals. I've pushed a fix to the core for this. The issue was not specific to Reno, but present on both admin themes. Please let me know if it persists there. Thanks. 

@somatonic The modal fix you linked was already taken care of awhile back.

**Comment by outflux3** [comment] 2016-08-17 23:34
awesome, will start updating all of the dev sites i'm working on and report back.
Wondering also if any fix i can apply to some select production sites where i can't update the core...

**Comment by isellsoap** [comment] 2016-09-30 06:53
@outflux3 This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 06:53 UTC
Labels: Fixed! Please Confirm
