### ISSUE TITLE
Pagelist Label format

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1719] opened 2016-03-04 15:26 UTC
![image](https://cloud.githubusercontent.com/assets/370148/13531157/5dcd3b14-e225-11e5-8d61-56f7da80d81c.png)

I have tried to use the new label format for templates. Which is nice, but as soon as I use that for a PagelistSelectMultple input, a page field is rendered as UL in the label of the selected pages.

{date} {title} (Lang: {language_published.title})

Also I didn't expect that the page list to select from also takes this custom label for it's labels for all pages, which usually in my case is different for every level.

**Comment by somatonic** [comment] 2016-03-04 15:36
So if I use the "title" as the label for the page field, also the page list tree's label all use the "title", and not the label format I defined in their respective templates. 

This really makes this combination kinda useless. I want the page list label to stay as they're are defined in their template and even be able to keep that for the selected items if possible. Now I have to define the same label in both places, with the undesirable effect that all pages's label get overwritten by this custom label. 

I guess that's only an issue with the PageListSelect input types, when being able to browse the tree on different levels.

**Comment by somatonic** [comment] 2016-03-04 15:42
I tried to use the ASMselect type, but then there's the UL markup too for the page field:

![image](https://cloud.githubusercontent.com/assets/370148/13531665/0197fe58-e228-11e5-837c-7d69fa7f3bb5.png)

**Comment by ryancramerdesign** [comment] 2016-04-05 12:13
Thanks @somatonic I've pushed a fix for this issue.

**Comment by isellsoap** [comment] 2016-09-30 07:02
@somatonic This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:02 UTC
Labels: Fixed
