### ISSUE TITLE
Creating a new template with (only) cyrillic chars causes empty template name and PW/DB errors. 

### ISSUE THREAD

**Issue by anilex** [ryancramerdesign/ProcessWire#1952] opened 2016-07-30 12:49 UTC
By mistake, I typed the new template name with Cyrillic characters and on save the error appear: 
`ProcessWire: ProcessTemplate: Template must be assigned a name before 'filename' can be accessed`

Then the admin panel > Templates tab couldn't be used. This happens to the latest PW devns, new installation, multilanguage version. 

The new row in the `templates` table was with empty `name` column. When I filled it up with something then everything was back to normal.

**Comment by ryancramerdesign** [comment] 2016-08-03 13:17
Thanks @anilex I've pushed a fix for this issue.

**Comment by isellsoap** [comment] 2016-09-30 07:07
@anilex This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:07 UTC
Labels: Fixed
