### ISSUE TITLE
CKEditor field doesn't save after inserting an image

### ISSUE THREAD

**Issue by Fokke-** [ryancramerdesign/ProcessWire#1335] opened 2015-08-11 10:50 UTC
When I add an image to the CKEditor field and try to save the page, the following alert will keep popping up:

**Confirm Navigation**
There are unsaved changes:
[field name here]
Are you sure you want to leave this page?

At the same time, this error appears in console:

`Uncaught IndexSizeError: Failed to execute 'extend' on 'Selection': 1 is larger than the given node's length. (ckeditor.js:396)`

When editing only text and not adding images, the field will save just fine.

Using 2.6.12 dev.
CKEditor is in inline mode.

**Comment by adrianbj** [comment] 2015-08-11 14:37
Looks like it might be an issue since CKEditor 4.4.6
http://ckeditor.com.rajatorrent.com/addon/divarea

Do you get the same problem in Firefox?

**Comment by Fokke-** [comment] 2015-08-12 13:34
In Firefox there's no problems at all.

In Chrome, Opera and Safari saving works if you unfocus the field before clicking Save.

**Comment by tbba** [comment] 2015-08-13 18:15
I think that this is related: The "Link" popup also behaves funny (under Safari/Mac) it does not save a new link any more.

**Comment by ryancramerdesign** [comment] 2015-08-14 12:56
I was seeing this error in a different context earlier this week. Inserting
image and clicking save immediately (before blurring CKE field) caused the
changes in an inline CKE field not to be saved. I looked at it further, and
it is apparently a bug in the current stable CKEditor. They are fixing it
in 4.5.3, which is supposed to be out next week. Though I've implemented a
workaround in this week's PW version, which is already on the dev branch.
The issue is that CKEditor's getData() method fails (and produces a JS
error) when called before the field is blurred, after certain conditions
(like inserting an image). That getData() method is where PW pulls the
inline editor data from on form submit. The workaround forces a blur and
focus on the CKE field when the form is submitted, which apparently resets
something in CKE that enables its getData() method to work again. You can
also workaround it by clicking outside the CKE inline editor field before
clicking the submit button, but obviously not something we'd expect people
to do.

**Comment by isellsoap** [comment] 2015-08-27 10:44
@Fokke- Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by nickbouton** [comment] 2015-11-27 19:25
@isellsoap I can confirm that upgrading CKEditor to 4.5.5 fixes this issue. Was having a similar issue with liferay/alloy-editor that was resolved when CKEditor was upgraded.

**Comment by isellsoap** [comment] 2016-03-10 07:33
@nickbouton Cool! Can you close the issue? Thank you!

**Closed** 2016-03-10 09:12 UTC
Labels: Fixed
