### ISSUE TITLE
Infinite page references issue

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1962] opened 2016-08-05 17:21 UTC
I'm not sure if this is really a "bug", but it's something that can happen if you're not careful and can cause an infinite loop and exhaust your server resources.

Let's say you have the following:
- 'product' template
- 'category' template

Let's say you have the following fields:
- single-select 'product' page field (allows you to select all pages with 'product' template); field assigned to 'category' template
- single-select 'category' page field (allows you to select all page with 'category' template); field assigned to 'product' template

Now let's say you've created some pages with the above and the data filled in for each field.

Assume the following in 'product.php' and view a page using 'product' template.:
```
<?php
$category = $page->category; // perhaps we assign it for convenience
echo $category->product->title; // causes infinite loop; obviously you're supposed to do $page->title
````

Can PW detect such an infinite loop and prevent it from happening?

(This is kind of similar to how browsers prevent pages that are accidentally redirecting to each other from going on forever.)

**Comment by isellsoap** [comment] 2016-09-30 21:13
@jlahijani Can this issue be closed?

**Comment by isellsoap** [comment] 2016-10-01 06:55
@jlahijani I close this issue as it doesn’t seem to be an issue which will be fixed (not a bug). If you think the issue requires additional work to do, please add a comment to this issue and I re-open it. Thank you.

**Closed by isellsoap** 2016-10-01 06:55 UTC
Labels: Conversation
