### ISSUE TITLE
Creating new field of type textlanguage on template edit doesn't add it

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1217] opened 2015-06-04 12:28 UTC
As the title says.

**Comment by somatonic** [comment] 2015-06-19 09:59
It seems most of the time this adding field on template isn't working. On occasion it seems to work though most of the time not.

**Comment by ryancramerdesign** [comment] 2015-06-28 10:43
So far I can't duplicate that. Are you saving your template after adding the field? That step is required. This particular feature was added by Adrian, and we can ask him to look at it if there is a way to reproduce.

**Comment by adrianbj** [comment] 2015-07-11 06:35
Hey guys - I will look into this shortly. 

Soma - can you confirm - is it creating the field, but just not adding it to the template, or is the field not even being created? Also, are you clicking the Save button the second time? First time creates the field, but the second time will save any additional field settings and then close the modal.

**Comment by teppokoivula** [comment] 2015-07-12 18:47
Could be related, so mentioning here. There's definitely some kind of inconsistency in this feature:

- Earlier today this created a field, but didn't add it to the template. After closing the modal window (Save didn't close it, just saved field settings, no matter how many times I tried) I had to refresh page to see it in the list of fields.
- Just a moment ago I did the same, except this time I created a field and hit "Save", then edited field settings and hit "Save" again.. and then hit "Save" one more time without making changes to the field. Suddenly the modal window disappeared and the field was instantly added to the template.
- Third attempt: after the second "Save", the modal closed and field was added. I did some changes to the field settings too, so that might've been just a coincidence in the second attempt, by the way.

**Comment by adrianbj** [comment] 2015-07-13 15:03
@teppokoivula - I think what you are seeing is expected behavior - closing the modal after the first save won't add the field to the template, nor will it add it to the dropdown list of available fields. You need to click save the second time for the field to be added to the template. If you think this is confusing I might be able to improve this - perhaps it could be added after the initial save - I would have to trigger slightly differently though as it needs the ID of the new field, so would have to be after the save, not on the initial click of the save button.

As for the issues @somatonic is having - I noticed them on one PW install but not others. Regardless, I think they should be fixed in this version:
https://gist.github.com/adrianbj/38324a9a08fe1241a373

I believe the issues were introduced when the new core PW modals were used with this feature, but not positive.

Please let me know if that works for you now.

**Comment by teppokoivula** [comment] 2015-07-13 16:57
@adrianbj Not sure I'm following you here. I listed three entirely different behaviours for this feature above. Third one sounded like the expected behaviour to me too, but what about the other ones.. they can't all be correct behaviour, right?

Also: the only reason I had to close the modal was, as I already explained, because Save wasn't doing anything ("no matter how many times I tried") :)

**Comment by adrianbj** [comment] 2015-07-13 17:04
Sorry - I think I might have misunderstood you a bit. Could you try that new version though (the gist I posted above) and see how that goes. I think most of the issues were related to get properly getting the ID of the newly created field. This new version fixes that, but I haven't ever experienced the issue of the second click on Save button not closing the modal, so not sure if that will be solved or not.

Thanks again for your time on this!

**Comment by teppokoivula** [comment] 2015-07-13 17:10
So far everything seems to run fine, but I'll report back if I see similar issues again. Thanks!

**Comment by adrianbj** [comment] 2015-07-13 17:17
Great to hear - thanks for testing and for keeping an eye out for any similar issues. 

@somatonic - does it solve the issues you were having also?

@ryancramerdesign - do you want a PR, or do you want to just grab that new version from my gist?

**Comment by adrianbj** [comment] 2015-07-25 15:49
@ryancramerdesign - can we have the new version I posted incorporated into the core soon? Sounds like it has solved the issues @teppokoivula was having here and here (https://github.com/ryancramerdesign/ProcessWire/issues/1293).

**Comment by ryancramerdesign** [comment] 2015-07-26 09:56
I've added this to dev – thanks Adrian!

**Comment by adrianbj** [comment] 2015-07-26 17:20
Thanks @ryancramerdesign - hopefully @somatonic will see this, test, and close this issue.

**Comment by isellsoap** [comment] 2016-09-30 08:52
@somatonic This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 08:52 UTC
Labels: Can't reproduce
