### ISSUE TITLE
Fatal Error when trying to add a new language

### ISSUE THREAD

**Issue by imad5000** [ryancramerdesign/ProcessWire#1895] opened 2016-06-26 03:55 UTC
![languages add](https://cloud.githubusercontent.com/assets/20147901/16360423/ee1debde-3b6a-11e6-9b0a-4f0f0a7847ac.png)

> Notice: Trying to get property of non-object in /var/www/html/representatives/ProcessWire-languages/ProcessWire-devns/wire/modules/LanguageSupport/ProcessLanguage.module on line 139 Catchable fatal error: Argument 2 passed to ProcessWire\InputfieldWrapper::insertBefore() must be an instance of ProcessWire\Inputfield, null given, called in /var/www/html/representatives/ProcessWire-languages/ProcessWire-devns/wire/modules/LanguageSupport/ProcessLanguage.module on line 170 and defined in /var/www/html/representatives/ProcessWire-languages/ProcessWire-devns/wire/core/InputfieldWrapper.php on line 258

> `Recoverable Fatal Error: Argument 2 passed to ProcessWire\InputfieldWrapper::insertBefore() must be an instance of ProcessWire\Inputfield, null given, called in /var/www/html/representatives/ProcessWire-languages/ProcessWire-devns/wire/modules/LanguageSupport/ProcessLanguage.module on line 170 and defined (line 258 of /var/www/html/representatives/ProcessWire-languages/ProcessWire-devns/wire/core/InputfieldWrapper.php) `

> This error message was shown because: site is in debug mode. ($config->debug = true; => /site/config.php). Error has been logged.

**Comment by imad5000** [comment] 2016-06-26 03:58
ProcessWire 3.0.23 devns © 2016

**Comment by ryancramerdesign** [comment] 2016-06-29 10:11
Thanks @imad5000 I've pushed a fix for this issue.

**Comment by isellsoap** [comment] 2016-09-30 07:07
@imad5000 This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:07 UTC
Labels: Fixed
