### ISSUE TITLE
Image Edit Modal page jumps when pressing tab

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#969] opened 2015-02-26 20:17 UTC
In Chrome when I press tab when the modal is open the page scrolls down due to focus on the buttons. Put cursor in dim inputs and press tab. I can't scroll to get it back. Didn't know this was an issue before we put that scroll stop (overflow:hidden) in body of page. :) 

Find reason why browsers hates us.

Maybe preventing tab to the save buttons? I'm not sure.

**Comment by adrianbj** [comment] 2015-02-26 20:39
For me the modal window is now resizing dynamically so that the buttons are always on the screen so I don't think I can replicate this - do you maybe have an old js file being cached?

**Comment by teppokoivula** [comment] 2015-02-27 07:33
If I hit tab a few times, the window scrolls so that only the lower half of the modal is visible (focus on buttons). Few more tabs, and the window scrolls up so that only the upper half of the modal is visible (focus on the "link to larger version" checkbox).

This actually used to be worse. Still rather weird, but at least the modal is now (kind of) usable even after hitting tab. Resizing the screen returns it to correct position :)

**Comment by somatonic** [comment] 2015-02-27 16:41
Yeah the modal was always fitting the screen. But the problem is with hitting tab that it focuses other elements and the page scrolls, so only half the modal is visible and since recently we added CSS to prevent scrolling of the page I can't scroll back.

**Comment by ryancramerdesign** [comment] 2015-03-04 15:02
I'm not sure I understand how to reproduce this one. If I hit tab in a modal window, the focus state jumps between the inputs, then to the modal window buttons at the bottom. But there is no movement of the window or anything like that. The behavior seems completely normal and no different than outside of a modal window. Is it exhibiting the behavior in some other browser? (I just tested in chrome and safari)

**Comment by teppokoivula** [comment] 2015-03-04 18:29
@ryancramerdesign Perhaps this helps: http://youtu.be/LZZsySxoyG4. The video is cropped slightly too much from the left side (sorry 'bout that), but vertically it's all there, so the window disappearing up/down is exactly what it looks like to me too.

First "tab" often makes the modal window disappear altogether, so that all I see is the black overlay on top of page edit, and second tab key returns it 50% visible, but in this case the window was about 50% visible for the whole the time.

**Comment by ryancramerdesign** [comment] 2015-03-04 18:42
Thanks for the video. I just re-traced your steps exactly (double clicking
right aligned image), but still can't duplicate it. I can hold down the tab
key all day and it just cycles between the inputs and the modal buttons. I
did however notice something unusual in your video. When you double clicked
the image, it appeared to highlight your entire textarea before it opened
the modal. Any idea why? I've never seen that before. I'm starting to
wonder if it might be an OS difference. I'm running on OS X Yosemite, but
will try testing on my wife's Windows 98/PC notebook when she gets home
from work.

**Comment by teppokoivula** [comment] 2015-03-04 19:05
OS X Yosemite here too, with Chrome 40.0.2214.115. Not entirely sure about the highlighting thing -- it's an inline CKEditor, I'm pretty sure that's how it's always behaved for me :)

I'm starting to think that it might be a browser thing, though. When I do the same with Firefox, there are in fact two notable differences: the highlight which you mentioned there is very different (perhaps it's just the effect, though) and more importantly the main issue itself is gone.

Looks like Firefox keeps the window in place at all costs, while Chrome prefers the weird up-and-down-jumping thing.

**Comment by ryancramerdesign** [comment] 2015-03-04 19:50
I was using regular editor, so just tried changing my editor to inline, but
no change. Is it possibly browser cache? Those plugin.js files can be
really tricky to get updated. I literally have to open Chrome developer
tools, click on the little gear icon, and check the box to "disable cache
when developer tools are open." Otherwise I find it pretty much impossible
to get the browser to see the new one. If it were PW referencing these
plugin files, I could just add a nocache string to them, but they are under
CKE's control, so it sometimes takes drastic measures.

**Comment by teppokoivula** [comment] 2015-03-04 20:47
I've cleared cache for Chrome (multiple times), rebooted the browser, tried with dev tools (and "nocache" setting there), no difference. Seems unlikely that this would be the reason.

Just a moment ago, while debugging with dev tools open, I tried minimise dev tools by dragging it to a smaller size.. and suddenly the tab jump issue was gone. Dragged the dev tools to a slightly larger size, and the issue was back. Apparently screen height / size is a factor here.

Sorry, that's probably not much of help, and I'm out of time for today. I should be able to debug this further tomorrow. By now it seems quite obvious that it's "just" some weird Chrome front-end bug (or feature, as the two are often practically undistinguishable).

**Comment by jlahijani** [comment] 2015-03-06 00:34
I'm having this issue too.  Windows 8, Chrome.

Video: https://vid.me/cKbs

**Comment by teppokoivula** [comment] 2015-03-06 06:03
One possible solution is mentioned in [this Foundation issue](https://github.com/zurb/foundation/issues/6066): applying `-webkit-backface-visibility: hidden;` to the form containing the crop tools (#selected_image_settings).

@ryancramerdesign: I'm testing this on one of my sites right now, and it does indeed fix the issue for me. I don't really understand *why*, though, so you might want to test carefully :)

**Comment by teppokoivula** [comment] 2015-03-06 06:05
Well, that's strange; looks like simply adding a link to an issue of another GitHub project also creates a reference. Not that it matters much, really, but wasn't expecting *that* to happen :)

**Comment by tbba** [comment] 2015-03-15 09:43
I did some quick research and found this:

If it is "jquery ui dialog", you are using, there are much complaints on the web about jumping modals in some jquery ui versions....
http://stackoverflow.com/questions/17212650/jquery-ui-dialog-jumps-to-the-bottom-of-page-in-chrome
(The  jQuery UI 1.10.3 you are using, is mentioned there as well as a trouble maker.)
I think that the jquery you are using for the backend is pretty dated, what about an update?

The guys at https://github.com/uikit/uikit seem to have a clever trick for modals, 

.uk-modal {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1010;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
  background: rgba(0, 0, 0, 0.6);
  opacity: 0;
  -webkit-transition: opacity 0.15s linear;
  transition: opacity 0.15s linear;
  touch-action: cross-slide-y pinch-zoom double-tap-zoom;
}

Maybe that direction is something to try? In my impression uikit is rock solid now with modals.

**Comment by tbba** [comment] 2015-03-15 10:02
ok I tried to update the JqueryUI in PW core with the lastest version,1.11.4. just to see what happens.
My problems with modals seem to be fixed with that version (this version also has a minified variant which has only half the download size)

**Comment by ryancramerdesign** [comment] 2015-03-15 10:34
I tried upgrading to 1.11.4 last week, but it completely broke modals for me (among other things). They were all absolute positioned top left, no longer centered in window. If I happened to be scrolled down the page at all, they weren't even visible (just the overlay background). So it seems like they might have changed a lot in the 1.11 versions that will take a lot of time to account for. I don't think we want that just yet for PW 2.6 unless there's no other way. Are you not seeing similar issues?

I did now just try upgrading to 1.10.4, and all seems to work well there. No idea if that version fixes the reported modal issue, but it's worth a try because it at least doesn't seem to break anything. The changelog also indicates some fixes to modals, so maybe this will do the trick. 

I have finally been able to see the issue reported here btw, just not consistently. Strangely, I've only been able to reproduce it remotely on one client site (and randomly), but not locally on dev sites, making it a bit hard to debug. So if a jQuery UI upgrade will resolve it that's definitely worthwhile.

**Comment by ryancramerdesign** [comment] 2015-03-15 10:37
I like the uikit modals quite a lot too, but the just aren't quite as powerful or configurable as the jQuery UI ones. We pretty much take advantage of everything jQuery UI modals can do... things like swapping out buttons dynamically and more. But for front-end use I'd be much more likely to choose the uikit ones.

**Comment by tbba** [comment] 2015-03-15 11:36
From the linked bug reports I read the 1.10.4 still has the scrolling problem?!?!?

OK I did a mistake by not replacing ALL JQ-UI, but that sometimes mistakes give a hint as well :)

On my PW core I have this situation:
JQ-UI-JS in core/modules shows as  v1.10.3 (did not touch anything here)
JQ-UI-CSS in core/template-admin is 1.10.4 (I only replaced this CSS with 1.11.4 just for testing)

I either have a funny cache phenomena or doing this made the modales work:
Mac: Safari Yosemite: OK
Mac: FF: OK
Mac: Chrome: OK
WIN: IE11: OK

Of course a version mismatch cannot be a final solution 
but somewhere in 1.11.4 seems to be the fix???

**Comment by teppokoivula** [comment] 2015-03-16 07:41
@ryancramerdesign, just checking: did you actually try the proposed fix I mentioned earlier? For me that fixes the issue entirely, so I'm a bit confused what's going on here. Did it not work for you? :)

**Comment by m-artin** [comment] 2015-03-19 14:49
I found a similar issue. The modal window disappears, when I want to select the numbers inside the input for width or height, in order to resize the image. 
mac: safari yosemite

![size](https://cloud.githubusercontent.com/assets/1139221/6732968/72cd6fba-ce4f-11e4-8c17-3fc9b41efee2.png)

**Comment by ryancramerdesign** [comment] 2015-03-20 13:47
@teppokoivula sorry I completely missed that before. I will try adding webkit-backface-visibility and sounds like that might do the trick. Thanks!

**Comment by isellsoap** [comment] 2016-09-30 13:52
@ryancramerdesign Did you add the CSS property?

@tbba @teppokoivula Can this issue be closed?

**Comment by teppokoivula** [comment] 2016-09-30 14:31
@isellsoap This was added by @ryancramerdesign in https://github.com/ryancramerdesign/ProcessWire/commit/6b8a328ada40463140b5c07492653288b56d1f51 and I'm no longer able to reproduce the jumping issue.

**Closed** 2016-09-30 14:32 UTC
Labels: Can't reproduce, Conversation
