### ISSUE TITLE
LanguageSupport module installs with compile error

### ISSUE THREAD

**Issue by jtherczeg** [ryancramerdesign/ProcessWire#629] opened 2014-09-03 07:29 UTC
I installed the downloaded dev branch version 2.4.17 without multi-language support. In the core modules I installed the Languages Support module which resulted the following error:

Compile Error: Cannot redeclare class LanguageSupportInstall (line 279 of C:\wamp\www\pwdev25\wire\modules\LanguageSupport\LanguageSupportInstall.php)

I returned to the Modules list by pressing Go Back in my browser's toolbar. The module seemed to be installed, but the Setup > Languages menu item was not created, so I cannot use the multi-language feature.

My environment: Apache 2.4.9, PHP 5.5.12, MySQL 5.6.17, Google Chrome 37.0

**Comment by isellsoap** [comment] 2015-08-20 04:45
@jtherczeg Can this issue be closed?

**Comment by isellsoap** [comment] 2016-03-10 07:27
@ryancramerdesign Since @jtherczeg doesn’t seem to be very active on GitHub, can you please close this issue? Thank you!

**Comment by isellsoap** [comment] 2016-09-30 06:59
@jtherczeg This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 06:59 UTC
Labels: Fixed
