### ISSUE TITLE
Bug: ProcessPageAdd throws an error if a custom class is used for a template

### ISSUE THREAD

**Issue by marvinscharle** [ryancramerdesign/ProcessWire#1244] opened 2015-06-19 19:27 UTC
Hi Ryan,

I've encountered a bug with ProcessPageAdd(.module) using a custom class name for a template. The bug is caused by a syntax error on line 591 (Because `$page` isn't initialized here).

Using `$template` instead of `$page->template` returns the correct result.

Here is my fix for it:

```php
$class = $template->pageClass ? $template->pageClass : 'Page';
```

**Comment by ryancramerdesign** [comment] 2015-06-28 12:28
Thanks–good find, I have updated and will include in this weeks commits. Strangely, PhpStorm wasn't showing $page as being out of scope, but clearly it is.

**Comment by isellsoap** [comment] 2015-08-27 10:42
@marvinscharle Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by isellsoap** [comment] 2016-03-10 07:31
@ryancramerdesign Can you close this issue?

**Comment by isellsoap** [comment] 2016-09-30 07:00
@marvinscharle This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:00 UTC
Labels: Fixed
