### ISSUE TITLE
The 'requiredLabel' code example in /wire/config.php is obsolete

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#1956] opened 2016-08-02 01:35 UTC
* $config->InputfieldWrapper = array(
    *	'useDependencies' => true,
    * 	'requiredLabel' => 'Missing required value', 
    *	);

The text for 'requiredLabel' cannot be set using using [this code](https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/config.php#L1009) any longer (the text is now translatable instead) and this has confused some people:
https://processwire.com/talk/topic/925-german-de-de/?do=findComment&comment=87848
https://processwire.com/talk/topic/9605-change-formfield-error-message/

**Comment by fuzenco** [comment] 2016-08-02 16:28
The problem I see is that if someone isn't using translation, then there's no simple way to override the "Missing required value." That config code is still showing in 3.0 dev. As with all things ProcessWire, I just expect a config override to work like all the other ones do.

**Comment by ryancramerdesign** [comment] 2016-08-03 13:50
Thanks, I've pushed a fix for this issue.

**Comment by fuzenco** [comment] 2016-08-05 21:55
Awesome! Thanks Ryan. Works great on 3.0.29.

**Comment by isellsoap** [comment] 2016-09-30 07:07
@Toutouwai This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:07 UTC
Labels: Fixed
