### ISSUE TITLE
CKEditor Extra Plugins checkbox unchecking problem at field settings

### ISSUE THREAD

**Issue by Rayden** [ryancramerdesign/ProcessWire#1215] opened 2015-06-03 11:04 UTC
While configuring the CKEditor settings on a Textarea field, i wanted to uncheck all the Extra Plugins.

By default the following plugins where found and checked

- pwimage (recommended)
- pwlink (recommended)
- sourcedialog

As soon i uncheck 2 of the 3 and press Save, it apears that the values are written to the database correctly (at least when it returns to the page, the two unchecked boxes are still unchecked)

Unchecking the third box (or unchecking all 3 boxes at the same time) will restore to all three boxes checked.

**Comment by ryancramerdesign** [comment] 2015-06-28 10:39
Thanks–I can confirm, and for this case, we actually require that at least one plugin is checked. But that was not clarified, so I am updating it to add a note to this effect.

**Comment by ryancramerdesign** [comment] 2015-06-28 10:39
Btw, if you have a need to literally have no plugins checked, I can always add a "none" plugin or something like that–just let me know.

**Comment by Rayden** [comment] 2015-06-29 09:15
A note mentioning that atleast one plugin needs to be checked might clarify the working behind it. I still find it a bit unlogic, while there are cases where it is desirable to have none of the extra plugins loaded, it should be possible to uncheck all of them. A solution where a "none" plugin can be choosen would be nice.

**Comment by isellsoap** [comment] 2015-08-27 11:01
@Rayden Has this issue been fixed? If yes it would be cool if you’d close it. Thanks, it’s much appreciated!

**Comment by Rayden** [comment] 2015-08-30 17:28
@ryancramerdesign @isellsoap I just tested it in the latest dev branch 2.6.14 but it still works the same. It is impossible to uncheck all plugins and remain that way after saving. (I think only Ryan can close issues)

**Comment by isellsoap** [comment] 2016-09-30 10:19
@Rayden This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 10:19 UTC
Labels: Completed
