### ISSUE TITLE
maxFilesize does not read from post_max_size if in bytes

### ISSUE THREAD

**Issue by ivangretsky** [ryancramerdesign/ProcessWire#1870] opened 2016-06-10 09:10 UTC
Good day!
I am in the same situation again as it is described in this [forum post](https://processwire.com/talk/topic/11084-exceeds-max-allowed-file-size-error-on-live-server/). The issue is that [this code](https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/modules/Inputfield/InputfieldFile/InputfieldFile.module#L126) does not work with post_max_size if defined in bytes (as it happened to be on all my shared hostings). Seems to be easy to fix this.

**Comment by ryancramerdesign** [comment] 2016-06-10 14:28
Thanks, I've pushed a fix for this issue.

**Comment by isellsoap** [comment] 2016-09-30 07:06
@ivangretsky This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 07:06 UTC
Labels: Fixed
