### ISSUE TITLE
ProcessProfile vs. Multilanguage Fields

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#2034] opened 2016-09-12 16:05 UTC
I detected a strange behaviour with multilanguage fields in template _user_. If I try to edit field values via ProcessProfile, the input is not processed correctly.

- **Case 1**
If the user language is set to default, the default language value is editable but not the second language value.

- **Case 2**
If the user language is set to the second language, the default language value is not editable but overwrites the value of second language.

This happens with any multilanguage text field.
Tested with PW 3.0.18 and PW 3.0.33

I assume that ProcessProfile doesn't support multilanguage fields. Would be nice to have multilanguage support here too.

**Comment by ryancramerdesign** [comment] 2016-09-21 13:05
I guess I hadn't considered use cases for multi-language fields in ProcessProfile before, but agree it would be nice to have. I've gone ahead and added it in the latest commit. Thanks.

**Comment by kixe** [comment] 2016-09-28 03:42
Thank you for the fast implementation.

**Comment by isellsoap** [comment] 2016-09-30 10:21
@kixe This issue seems to be fixed, thus I close it. If you think the issue isn’t fixed yet or requires additional work to do, please consider reopening it.

**Closed by isellsoap** 2016-09-30 10:21 UTC
Labels: Completed

**Comment by kixe** [comment] 2016-09-30 10:33
@isellsoap I assume it is fixed. No time to test and confirm.
